FROM apache/airflow:2.8.0-python3.11

USER root

RUN apt-get update && apt-get install -y libgomp1 curl && rm -rf /var/lib/apt/lists/*

USER airflow

COPY docker/requirements-airflow.txt /tmp/requirements-airflow.txt
RUN pip install --no-cache-dir -r /tmp/requirements-airflow.txt

USER root

COPY docker/airflow-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

USER airflow
